### ISSUE TITLE
Code is uploaded to screeps.com even though TSC Errors

### ISSUE THREAD

**Issue by staal** [screepers/screeps-typescript-starter#56] opened 2017-06-03 15:19 UTC
Expected behaviour:
On actual errors (such as putting in a bogus word, "wooo" in the middle of code), no upload to the screeps server should occur.

This is not what is happening currently. I tested by downloading the source, setting credentials running:

```
yarn
git init
git add *
git commit -m "test"
npm run deploy
```

No errors. Simulator runs fine. Add bogus word "woo" in the middle of main.ts and run:
npm run deploy

Now the simulator fails with error:

```
[5:18:33 PM]ReferenceError: wooooooo is not defined
    at mloop:1377:5
    at Object.wrap:1887:12
    at Object.module.exports.Object.defineProperty.value:1392:56
    at __webpack_require__:21:30
    at __webpack_require__:21:30
    at module.exports.exports.getArg:67:18
    at main:70:10
    at eval:3829:4

```

Full build output:
```

Staal@pc MINGW64 /f/screeps-typescript-starter-master (master)
$ npm run deploy

> screeps-starter@2.0.0 deploy F:\screeps-typescript-starter-master
> webpack --colors --env.ENV=dev

clean-webpack-plugin: F:\screeps-typescript-starter-master\dist\dev\* has been removed.

[at-loader] Using typescript@2.3.4 from typescript and "tsconfig.json" from F:\screeps-typescript-starter-master\tsconfig.json.


[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 1 errors
Hash: 5af8dd5b84150d22ffd1
Version: webpack 2.6.1
Time: 3253ms
      Asset    Size  Chunks             Chunk Names
    main.js  121 kB       0  [emitted]  main
main.js.map  158 kB       0  [emitted]  main
   [0] ./~/source-map/lib/util.js 10.5 kB {0} [built]
   [1] ./src/config/config.ts 657 bytes {0} [built]
   [2] ./src/lib/logger/log.ts 5.53 kB {0} [built]
   [3] ./src/lib/logger/logLevels.ts 386 bytes {0} [built]
   [4] ./~/source-map/lib/array-set.js 2.76 kB {0} [built]
   [5] ./~/source-map/lib/base64-vlq.js 4.71 kB {0} [built]
   [6] ./~/source-map/lib/source-map-generator.js 13.4 kB {0} [built]
   [7] ./src/main.ts 1.04 kB {0} [built] [1 warning]
  [11] ./~/screeps-profiler/screeps-profiler.js 8.72 kB {0} [built]
  [13] ./~/source-map/lib/binary-search.js 4.25 kB {0} [built]
  [14] ./~/source-map/lib/mapping-list.js 2.34 kB {0} [built]
  [16] ./~/source-map/lib/source-map-consumer.js 38.4 kB {0} [built]
  [17] ./~/source-map/lib/source-node.js 13.5 kB {0} [built]
  [18] ./~/source-map/source-map.js 405 bytes {0} [optional] [built]
  [20] multi ./src/main.ts 28 bytes {0} [built]
    + 6 hidden modules

WARNING in ./src/main.ts
F:/screeps-typescript-starter-master/src/main.ts
ERROR: 28:3   no-unused-expression  unused expression, expected an assignment or function call
ERROR: 28:11  semicolon             Missing semicolon

 @ multi ./src/main.ts

ERROR in [at-loader] ./src/main.ts:28:3
    TS2304: Cannot find name 'wooooooo'.

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "deploy"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! screeps-starter@2.0.0 deploy: `webpack --colors --env.ENV=dev`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the screeps-starter@2.0.0 deploy script 'webpack --colors --env.ENV=dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the screeps-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --colors --env.ENV=dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs screeps-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls screeps-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\screeps-typescript-starter-master\npm-debug.log

```

**Comment by resir014** [comment] 2017-06-03 16:20
Related: #49.

I'm assuming this is part of the issue where Webpack is not aborting the build whenever a command in the chain errors out. But in case that's not what's going on here, I'll keep both threads open for now.

**Comment by bryanbecker** [comment] 2017-06-04 06:01
Thanks @staal 
~I'm going to close this as a duplicate of #49~ Ha, forgot I can't close

Feel free to leave suggestion in there, as each potential solution has tradeoffs based on how webpack works (async)

If you add `--bail` to the command in `package.json`, webpack will abort, but this also breaks watch mode.  A workaround you could use is unhook "uploading" from watch mode, and add `--bail` to your upload task

**Closed as completed** 2017-06-15 03:22 UTC
Labels: duplicate
