### ISSUE TITLE
'npm run local' throws error after fresh clone and following guide

### ISSUE THREAD

**Issue by pathurs** [screepers/screeps-typescript-starter#70] opened 2017-09-13 11:58 UTC
I can probably figure this out myself, however I could not see any answers to this on the supplied wiki and guides.

(It's pretty late at night, so I'm not in the mood to fully debug)

I believe that tslint, webpack, etc are not command that the command line can run:

```
'tslint' is not recognised as an internal or external command, operable program or batch file.
```

Here is my npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'local' ]
2 info using npm@3.3.12
3 info using node@v5.4.0
4 verbose run-script [ 'prelocal', 'local', 'postlocal' ]
5 info lifecycle screeps-typescript-starter@2.0.0~prelocal: screeps-typescript-starter@2.0.0
6 silly lifecycle screeps-typescript-starter@2.0.0~prelocal: no script for prelocal, continuing
7 info lifecycle screeps-typescript-starter@2.0.0~local: screeps-typescript-starter@2.0.0
8 verbose lifecycle screeps-typescript-starter@2.0.0~local: unsafe-perm in lifecycle true
9 verbose lifecycle screeps-typescript-starter@2.0.0~local: PATH: D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\GitHub\screeps-typescript-starter\node_modules\.bin;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\ProgramData\Razer\SwitchBlade\SDK;C:\Users\user\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\Program Files\nodejs\;C:\Prog;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;D:\Program Files\PuTTY\;C:\Users\user\AppData\Roaming\npm;C:\Users\user\AppData\Local\Microsoft\WindowsApps;D:\Program Files\php;D:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\user\AppData\Local\GitHubDesktop\bin;D:\Users\user\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin
10 verbose lifecycle screeps-typescript-starter@2.0.0~local: CWD: D:\GitHub\screeps-typescript-starter
11 silly lifecycle screeps-typescript-starter@2.0.0~local: Args: [ '/d /s /c', 'webpack --colors --env.ENV=local' ]
12 silly lifecycle screeps-typescript-starter@2.0.0~local: Returned: code: 1  signal: null
13 info lifecycle screeps-typescript-starter@2.0.0~local: Failed to exec local script
14 verbose stack Error: screeps-typescript-starter@2.0.0 local: `webpack --colors --env.ENV=local`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid screeps-typescript-starter@2.0.0
16 verbose cwd D:\GitHub\screeps-typescript-starter
17 error Windows_NT 10.0.14393
18 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "local"
19 error node v5.4.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error screeps-typescript-starter@2.0.0 local: `webpack --colors --env.ENV=local`
22 error Exit status 1
23 error Failed at the screeps-typescript-starter@2.0.0 local script 'webpack --colors --env.ENV=local'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the screeps-typescript-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack --colors --env.ENV=local
23 error You can get their info via:
23 error     npm owner ls screeps-typescript-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by pathurs** [comment] 2017-09-13 12:12
Turns out I had to update NPM and Node to latest.

Perhaps consider requiring specific versions of these, and adding this to the FAQ, or mentioning it somewhere :)

**Comment by resir014** [comment] 2017-09-13 12:49
@pathurs Sorry about that! I did mention on the readme that "latest LTS
version" of node is recommended, but I'll admit it's a little vague.

I'll change it when I'm out of work to be more clearer. Technically you
should be fine with anything above Node v6.0.0.

**Comment by pathurs** [comment] 2017-09-14 04:31
Wasn't a huge problem, however knowing that this is intended for "noobs", then I figured someone in my situation without my knowledge could have been 10x more confused

**Comment by wolffman122** [comment] 2017-10-24 00:30
Think I am still having similar error but attaching my log file.  I Just updated node which node is at 8.7.0  and npm is at 5.4.2.   The only other strange thing when I do npm install it says typings is depcrated not sure if that is a problem.  Any help would be appreciated.

[2017-10-24T00_35_10_244Z-debug.log](https://github.com/screepers/screeps-typescript-starter/files/1409137/2017-10-24T00_35_10_244Z-debug.log)

**Comment by resir014** [comment] 2017-10-24 00:49
@wolffman122 What did the console say before throwing out the error? If it's the same as above, try installing `tslint` and `webpack` globally.

Also, `typings` is in fact, deprecated since the typing system is moved over to `@types/` and built-in typings within packages. The reason we're still using `typings` is we still need to wait up for the type declarations that we use to be published to DefinitelyTyped.

https://github.com/screepers/Screeps-Typescript-Declarations/pull/120

**Comment by wolffman122** [comment] 2017-10-24 00:52
![image](https://user-images.githubusercontent.com/19178872/31919995-0d09d0d4-b834-11e7-8725-950a95d184cf.png)

![image](https://user-images.githubusercontent.com/19178872/31920000-1d0df154-b834-11e7-83cd-c5d21e7bfbee.png)

@resir014  also do you have any instructions on installing those two things I am not to familiar how to?

**Comment by resir014** [comment] 2017-10-24 00:54
@wolffman122 Hmm. It seems your credentials.json file might be broken. Try
deleting the keys that are blank and try again.

**Comment by wolffman122** [comment] 2017-10-24 00:59
@resir014  i have my credentials.json open and put my emailin, then password, do i have to put anything in for TOKEN or SERVER_PASS if i am doing this on the production screeps server?  Not sure where the keys you are referring to are

**Comment by resir014** [comment] 2017-10-24 01:04
Ah yeah, TOKEN and SERVER_PASS are meant for private servers only, so
remove those keys.

This was undocumented and the common source of issues. I'll try to document
later when I've arrived at my workplace.

**Comment by wolffman122** [comment] 2017-10-24 01:08
@resir014  worked thank you so much

**Comment by resir014** [comment] 2017-10-24 01:23
@wolffman122 You're welcome!

I'm going to close this issue later since the issues here are mostly trivial and can be fixed by improving the documentation. It's not perfect, but I'm open for improvements to the docs.

**Comment by ChrisTaylorRocks** [comment] 2017-10-24 01:53
The latest build has errors helped people on slack with the version from 9/14 and works fine.
Output from `npm run local`
https://hastebin.com/aqahutajoy.lua

**Comment by resir014** [comment] 2017-10-24 03:02
Confirmed working as per the Slack discussion earlier. Closing this now.

**Closed as completed by resir014** 2017-10-24 03:02 UTC
